name: kkiapay_flutter_sdk
description: KkiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.2.6
support: kkiapay <support@kkiapay.me>
homepage: "https://github.com/kkiapay/kkiapay-flutter-sdk"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  url_launcher: ^6.1.14
  http: ^1.1.0
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  stacked_generator:

flutter:
  uses-material-design: true
