name: kkiapay_flutter_sdk
description: KKiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.3.0-dev.1
homepage: "https://kkiapay.me/"

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  stacked_shared:
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  url_launcher: ^6.2.5           # using for wave payment
  http: ^1.2.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  stacked_generator:

flutter:
  uses-material-design: true
