name: kkiapay_flutter_sdk
description: KkiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.2.6
support: kkiapay <support@kkiapay.me>
homepage: "https://github.com/kkiapay/kkiapay-flutter-sdk"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1+1
  stacked_services:
  url_launcher:
  http:
  webview_flutter: ^3.0.4
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  stacked_generator:

flutter:
  uses-material-design: true
