name: Workflow test
on: push

jobs:
  package-publishing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: ">> Flutter package <<"
        uses: k-paxian/dart-package-publisher@v1.4
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: flutter.package
          dryRunOnly: true
