name: Publish KkiaPay flutter sdk to Pub.dev
on: push

jobs:
  package-publishing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: ">> Flutter package <<"
        uses: k-paxian/dart-package-publisher@v1.4
        
      - name: Install dependencies
        run: dart pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: dart pub publish --force
